server:
  port: 9050
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://192.168.31.160:3307/test?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: warn
    com:
      sleepy: info